from ..schemas import ItineraryRequest, ItineraryResponse, ItineraryItem
from .external_apis import fetch_places, fetch_travel_options
from .llm import request_ai_itinerary

async def build_itinerary(request: ItineraryRequest) -> ItineraryResponse:
    destination = request.preference.city
    days = request.preference.days
    chaos = request.preference.chaos_level
    interests = request.preference.interests

    external_places = await fetch_places(destination, interests)
    travel_options = await fetch_travel_options(destination)

    prompt_data = {
        "destination": destination,
        "days": days,
        "chaos_level": chaos,
        "interests": interests,
        "places": external_places,
        "travel_options": travel_options,
    }

    ai_response = await request_ai_itinerary(prompt_data)

    itinerary_items = [
        ItineraryItem(**item) for item in ai_response.get("itinerary", [])
    ]

    return ItineraryResponse(
        destination=destination,
        total_days=days,
        chaos_level=chaos,
        itinerary=itinerary_items,
        notes=ai_response.get("notes", "Generated by Crazy Itinerary Generator."),
    )
